config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'postulacion/crear/:id',to: 'postulations#create',as: :postulation_create
resources :jobs

  devise_for :users, :controllers => {
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/job.rb
class Job < ApplicationRecord
  def self.ransackable_attributes(auth_object = nil)
    ["name"]
end

def self.ransackable_associations(auth_object = nil)
    ["users"]
end
  #RELACIONES
  belongs_to :user
  has_many :postulations, dependent: :destroy
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_job, only: %i[ show edit update destroy ]
  before_action except: [:index, :show] do
    authorize_request(["admin"])
  end
  # GET /jobs or /jobs.json
  def index
    @q = Job.ransack(params[:q])
    @jobs = @q.result(distinct: true)
    @postulations = Postulation.all
  end

  # GET /jobs/1 or /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs or /jobs.json
  def create
    @job = Job.new(job_params)
    @job.user = current_user
    respond_to do |format|
      if @job.save
        format.html { redirect_to job_url(@job), notice: "Job was successfully created." }

      else
        format.html { render :new, status: :unprocessable_entity }

      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to job_url(@job), notice: "Job was successfully updated." }

      else
        format.html { render :edit, status: :unprocessable_entity }

      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Job was successfully destroyed." }

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:name, :description)
    end

    def verify_ofert_user
      unless @job == current_user
        return root_path
      end
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job) do |form| %>
  <% if job.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %>

app/views/jobs/_job.html.erb
<div id="<%= dom_id job %>">
  <p>
    <strong>Nombre:</strong>
    <%= job.name %>
  </p>

  <p>
    <strong>Descripción:</strong>
    <%= job.description %>
  </p>

  <p>
    <strong>Escrito por :</strong>
    <%= job.user.email %>
  </p>

</div>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render "form", job: @job %>

<br>

<div>
  <%= link_to "Show this job", @job %> |
  <%= link_to "Back to jobs", jobs_path %>
</div>

app/views/jobs/index.html.erb
<div class="container">  

  <h1>Jobs</h1>
  <% if user_signed_in?#si esta logeado %>
    <div>

      <span class="fs-4 fw-bold"> Bienvenido estimado/a : <%= current_user.email %></span>

      <% if current_user.avatar.attached? %>
        <%= image_tag current_user.avatar, width:300 %>
      <% end %>
      
    </div>
    <!--ADMIN-->
    <% if current_user.roles == "admin" %>
      <p>Dashboard <%= current_user.roles %> </p>
      <%= link_to "Nuevo trabajo", new_job_path %>
    <% else %>
      <!--CLIENTE-->
      <p>Dashboard <%= current_user.roles %> </p>
    <% end %>
  <% end %>
  <div>
        <%= search_form_for @q do |f| %>
        <%= f.search_field :name_cont %>
        <%= f.submit %>
      <% end %>
  </div>
  <div id="jobs">
    <% if @jobs.length>=1 %>
      <% @jobs.each do |job| %>
        <%= render job %>
        <p>
          <%= link_to "Ver más..", job %>
        </p>
        <hr>
      <% end %>
    <% else %>
      <p> No se ha encontrado jobs </p>
    <% end %>
  </div>
  <% if user_signed_in?%>
    <% if current_user.roles == "admin"%>
      <h3>Ofertas notificadas</h3>
      <% @postulations.each do |p|%>
        <div>
          <h4>Oferta: <%= p.job.name %>  </h4>
          <p>Usuario solicitado: <%= p.user.name %></p>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/jobs/new.html.erb
<div class="container">
  <h1>Crear Oferta laboral</h1>

  <%= render "form", job: @job %>

  <br>

  <div>
    <%= link_to "Back to jobs", jobs_path %>
  </div>
</div>

app/views/jobs/show.html.erb
<div class="container">

  <%= render @job %>

  <div>
      <% if @job.user_id == current_user.id %>
        <%= link_to "Editar job", edit_job_path(@job) %> 
      <% end %>
      <%= link_to "Back to jobs", jobs_path %>

    <% if @job.user_id == current_user.id %>

      <%= button_to "Eliminar job", @job, method: :delete %>
      
    <% end %>

      <%= link_to "Postular", postulation_create_path(@job) %>

  </div>
</div>